export const surpriseMePrompts = [
  'Responsive Design Icon',
  'Coding Ninja Logo',
  'Magnifying Glass Code Search',
  'Abstract Agile Development Logo',
  'Futuristic Globe Circuit Board',
  'Rocket Launch Code Exhaust',
  'Pencil and Server Code Editing',
  'CSS Shield Logo',
  'API Interconnected Nodes Icon',
  'JavaScript Dynamic Web Page Logo',
  'Bug Fixing Superhero Icon',
  'Server Rack with Glowing Lights',
  'Abstract Cloud Computing Logo',
  'Command-Line Interface (CLI) Icon',
  'Wireframe Globe Connectivity',
  'Evolving Browser Development Tool',
  'HTML Keyhole Unlocking Possibilities',
  'Teamwork Logo with Code Bubbles',
  'Robot Hand Crafting Website Icon',
  'Server Stack Functionality Layers',
  'Futuristic AI Assistant Code Guide',
  'Pixelated Heart for Coding Love',
  'Version Control Branching Pathways',
  'Dynamic Pie Chart Visualization',
  'Open Book with Code Snippets',
  'Cybersecurity Shield Icon',
  'Responsive Grid Transforming Devices',
  'Clock Symbolizing Timely Development',
  'Abstract Puzzle Piece Code Completion',
  'Gear and Pen Creative Development',
  'Virtual Reality Headset Coding Realm',
  'Futuristic Holographic Code Interface',
  'Minimalistic Browser Window Icon',
  'Pixel Art Robot for Coding Tasks',
  'Abstract Maze with Efficient Code Path',
  'Code Editor Icon with Syntax Highlighting',
  'Dynamic Waveform Real-Time Interaction',
  'API Key Unlocking Developer Potential',
  'Skyscraper with Coding Windows Logo',
  'Binary Code Developer Handshake',
  'Pixelated Rocket Ship Icon',
  'Browser Bookmark with Coding Symbols',
];